/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SalesImport } from './routes/sales'
import { Route as DrinksImport } from './routes/drinks'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SalesRoute = SalesImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRoute,
} as any)

const DrinksRoute = DrinksImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksImport
      parentRoute: typeof rootRoute
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drinks': typeof DrinksRoute
  '/sales': typeof SalesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drinks': typeof DrinksRoute
  '/sales': typeof SalesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/drinks': typeof DrinksRoute
  '/sales': typeof SalesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drinks' | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drinks' | '/sales'
  id: '__root__' | '/' | '/drinks' | '/sales'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrinksRoute: typeof DrinksRoute
  SalesRoute: typeof SalesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrinksRoute: DrinksRoute,
  SalesRoute: SalesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/drinks",
        "/sales"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/drinks": {
      "filePath": "drinks.tsx"
    },
    "/sales": {
      "filePath": "sales.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
